

    - name: Run test suite
      run: |
        composer test
        npm test
        npm run build
        git status
        git status | grep "nothing to commit, working tree clean"

    - name: Codecov
      uses: codecov/codecov-action@v5
